# Generated by Django 2.2.8 on 2019-12-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineering',
            name='text',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='masters',
            name='text',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='puc',
            name='text',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='sslc',
            name='text',
            field=models.TextField(default=True),
        ),
    ]
