# Generated by Django 2.2.7 on 2019-12-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191212_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslc',
            name='category',
            field=models.CharField(choices=[('SSLC', 'SSLC'), ('PUC', 'PUC'), ('Engineering', 'Engineering'), ('Masters', 'Masters')], default=True, max_length=20),
        ),
    ]
